name: Node7 Sovereign Build
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Freeing RAM
        run: |
          sudo rm -rf /usr/share/dotnet /opt/ghc "/usr/local/share/boost"
          sudo rm -rf /usr/local/lib/android /usr/local/share/powershell
          docker image prune -a -f

      - name: Build with Buildozer
        uses: kivy/buildozer-action@master
        with:
          command: buildozer android debug
          repository_root: .
